# Pandas

In [67]:
import pandas as pd

In [68]:
pd.__version__

'1.5.3'

In [69]:
a=pd.Series([2,3,4,5],index=["a","b","c","d"])#S capital for series

In [70]:
type(a.values)

numpy.ndarray

In [71]:
type(a)

pandas.core.series.Series

In [72]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [73]:
a['a']

2

In [74]:
a['a':'d']#if you slice using explicit indices

a    2
b    3
c    4
d    5
dtype: int64

In [75]:
#second way to create series is create a dict and then make series of it like:
dict={1:33,2:56,3:78}
a=pd.Series(dict)

In [76]:
a

1    33
2    56
3    78
dtype: int64

In [77]:
grades_dict={"A":4,"B":3.5,"C":3,"D":2.5}
grades=pd.Series(grades_dict)

In [78]:
grades

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [79]:
marks_dict={"A":85,"B":75,"C":65,"D":55}
marks=pd.Series(marks_dict)
marks

A    85
B    75
C    65
D    55
dtype: int64

In [80]:
marks[0:2]#access data using explicit or implicit both

A    85
B    75
dtype: int64

In [81]:
D=pd.DataFrame({'Marks':marks,'Grades':grades})

In [82]:
D

   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [83]:
D.T

           A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [84]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [85]:
D.values[2,0]

65.0

In [86]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [87]:
import numpy 
D['Scaled Marks']=numpy.round(90*(D['Marks']/100))

In [88]:
D

   Marks  Grades  Scaled Marks
A     85     4.0          76.0
B     75     3.5          68.0
C     65     3.0          58.0
D     55     2.5          50.0

In [89]:
E=D[D['Marks']>70]

In [90]:
E

   Marks  Grades  Scaled Marks
A     85     4.0          76.0
B     75     3.5          68.0

In [91]:
names_dict={1:'Gunjan',2:'Naman',3:'Sanjay',4:'Sonia',5:'Pratik'}
names=pd.Series(names_dict)

In [92]:
vaccined_dict={1:'F',2:'T',3:'T',4:'T',5:'T'}
vaccined=pd.Series(vaccined_dict)

In [93]:
DF=pd.DataFrame({'Names':names,'Vaccined':vaccined})
DF

    Names Vaccined
1  Gunjan        F
2   Naman        T
3  Sanjay        T
4   Sonia        T
5  Pratik        T

In [95]:
M=DF[DF['Vaccined']=='T']

In [96]:
M

    Names Vaccined
2   Naman        T
3  Sanjay        T
4   Sonia        T
5  Pratik        T

In [98]:
A=pd.DataFrame([{'a':1,'b':3},{'b':-3,'c':4}])

In [99]:
A

     a  b    c
0  1.0  3  NaN
1  NaN -3  4.0

In [106]:
A.fillna(0)

     a  b    c
0  1.0  3  0.0
1  0.0 -3  4.0

In [109]:
A.dropna()#causes data loss (drops all the rows with NaN)

Empty DataFrame
Columns: [a, b, c]
Index: []